"""
Pytest configuration and fixtures for Assessment API tests
"""
import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, String, JSON, event
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool
from sqlalchemy.dialects.postgresql import UUID
import os
import sys
from pathlib import Path
import uuid as uuid_module

# Add src directory to Python path
src_path = Path(__file__).parent.parent / "src"
sys.path.insert(0, str(src_path))

from api.main import app
from api.dependencies.auth import get_assessment_access_context
from database.connection import get_db
from utils.assessment_access_context import AssessmentAccessContext
from database.models import (
    Base,
    Question,
    Option,
    BspStyle,
    Assessment,
    AssessmentScore,
    AssessmentScoreStyle,
    QuestionResponse,
    QuestionType as DbQuestionType,
    SituationType as DbSituationType,
    LifeContextType as DbLifeContextType,
)


def four_options_for_question_order(_question_order: int) -> list:
    """Four options (red/green/blue/grey); option_key is generated by the API."""
    return [
        {
            "color": "red",
            "option_text": "Sample red option text for testing purposes",
            "display_order": 1,
        },
        {
            "color": "green",
            "option_text": "Sample green option text for testing purposes",
            "display_order": 2,
        },
        {
            "color": "blue",
            "option_text": "Sample blue option text for testing purposes",
            "display_order": 3,
        },
        {
            "color": "grey",
            "option_text": "Sample grey option text for testing purposes",
            "display_order": 4,
        },
    ]


# bsp_styles uses PostgreSQL text[] in production; SQLite tests use JSON columns for the same fields.
_BSP_STYLE_ARRAY_COLUMNS = frozenset(
    {
        "environmental_preferences",
        "interaction_preferences",
        "character_strengths",
        "psychological_needs",
        "likes",
        "dislikes",
        "work_preferences",
        "warning_signs",
    }
)


# Use in-memory SQLite for testing
SQLALCHEMY_TEST_DATABASE_URL = "sqlite:///:memory:"

@pytest.fixture(scope="function")
def test_db():
    """
    Create a fresh in-memory database for each test
    """
    engine = create_engine(
        SQLALCHEMY_TEST_DATABASE_URL,
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )

    @event.listens_for(engine, "connect")
    def _sqlite_enable_foreign_keys(dbapi_connection, _connection_record):
        if SQLALCHEMY_TEST_DATABASE_URL.startswith("sqlite"):
            cursor = dbapi_connection.cursor()
            cursor.execute("PRAGMA foreign_keys=ON")
            cursor.close()
    
    # Monkey-patch UUID columns to use String for SQLite
    # This is necessary because SQLite doesn't have a native UUID type
    for table in Base.metadata.tables.values():
        for column in table.columns:
            if isinstance(column.type, UUID):
                column.type = String(36)
            elif (
                column.table.name == "bsp_styles"
                and column.name in _BSP_STYLE_ARRAY_COLUMNS
            ):
                column.type = JSON()
    
    # Auto-generate UUIDs for SQLite (PostgreSQL does this automatically)
    @event.listens_for(Question, 'before_insert')
    def generate_question_id(mapper, connection, target):
        if target.id is None:
            target.id = str(uuid_module.uuid4())
    
    @event.listens_for(Option, 'before_insert')
    def generate_option_id(mapper, connection, target):
        if target.id is None:
            target.id = str(uuid_module.uuid4())
        # Ensure question_id is string for SQLite
        if hasattr(target.question_id, '__str__') and not isinstance(target.question_id, str):
            target.question_id = str(target.question_id)
    
    @event.listens_for(BspStyle, 'before_insert')
    def generate_bsp_style_id(mapper, connection, target):
        if target.id is None:
            target.id = str(uuid_module.uuid4())

    @event.listens_for(Assessment, "before_insert")
    def generate_assessment_id(mapper, connection, target):
        if target.id is None:
            target.id = str(uuid_module.uuid4())

    @event.listens_for(QuestionResponse, "before_insert")
    def generate_question_response_id(mapper, connection, target):
        if target.id is None:
            target.id = str(uuid_module.uuid4())
        if hasattr(target.assessment_id, "__str__") and not isinstance(target.assessment_id, str):
            target.assessment_id = str(target.assessment_id)
        if hasattr(target.option_id, "__str__") and not isinstance(target.option_id, str):
            target.option_id = str(target.option_id)

    @event.listens_for(AssessmentScore, "before_insert")
    def generate_assessment_score_id(mapper, connection, target):
        if target.id is None:
            target.id = str(uuid_module.uuid4())
        elif not isinstance(target.id, str):
            target.id = str(target.id)
        if hasattr(target.assessment_id, "__str__") and not isinstance(target.assessment_id, str):
            target.assessment_id = str(target.assessment_id)

    @event.listens_for(AssessmentScoreStyle, "before_insert")
    def generate_assessment_score_style_id(mapper, connection, target):
        if target.id is None:
            target.id = str(uuid_module.uuid4())
        elif not isinstance(target.id, str):
            target.id = str(target.id)
        if hasattr(target.assessment_score_id, "__str__") and not isinstance(
            target.assessment_score_id, str
        ):
            target.assessment_score_id = str(target.assessment_score_id)
    
    # Create all tables
    Base.metadata.create_all(bind=engine)
    
    TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    
    yield TestingSessionLocal
    
    # Drop all tables after test
    Base.metadata.drop_all(bind=engine)


@pytest.fixture(scope="function")
def client(test_db):
    """
    Create a test client with overridden database dependency
    """
    def override_get_db():
        try:
            db = test_db()
            yield db
        finally:
            db.close()
    
    def _test_assessment_ctx() -> AssessmentAccessContext:
        sub = "test-cognito-sub"
        return AssessmentAccessContext(cognito_sub=sub, visible_user_ids=frozenset({sub}))

    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_assessment_access_context] = _test_assessment_ctx

    with TestClient(app) as test_client:
        yield test_client
    
    app.dependency_overrides.clear()


@pytest.fixture
def sample_question_data():
    """Sample question + four options for POST /questions"""
    return {
        "question_text": "I want my workspace to be",
        "type": "environmental_preferences",
        "situation": "typical",
        "life_context": "professional",
        "question_order": 1,
        "version": 1,
        "is_active": True,
        "options": four_options_for_question_order(1),
    }


@pytest.fixture
def bare_question_id(test_db):
    """
    Create a question row with no options (for tests of POST /options in isolation).
    question_order starts high to avoid colliding with API-created questions.
    """
    counter = {"n": 9000}

    def _make():
        counter["n"] += 1
        db = test_db()
        try:
            q = Question(
                question_order=counter["n"],
                question_text="Bare question text for isolated option API tests here",
                type=DbQuestionType.environmental_preferences,
                situation=DbSituationType.typical,
                life_context=DbLifeContextType.professional,
                version=1,
                is_active=True,
            )
            db.add(q)
            db.commit()
            db.refresh(q)
            return str(q.id)
        finally:
            db.close()

    return _make


@pytest.fixture
def sample_option_data():
    """Sample option data for testing (requires question_id to be set)."""
    return {
        "color": "red",
        "option_text": "Organized yet flexible",
        "display_order": 1,
    }


@pytest.fixture
def sample_bsp_style_data():
    """Sample BSP style data for testing"""
    return {
        "style_number": 1,
        "title": "The Organizer",
        "has_video": True,
        "youtube_video_id": "dQw4w9WgXcQ",
        "description": "Systematic and detail-oriented",
        "display_order": 1,
        "environmental_preferences": ["Structured and organized spaces"],
        "interaction_preferences": ["Clear communication and planning"],
        "character_strengths": ["Reliability", "organization", "attention to detail"],
        "psychological_needs": ["Order", "predictability", "clear expectations"],
        "likes": ["Systems", "schedules", "clarity"],
        "dislikes": ["Chaos", "ambiguity", "last-minute changes"],
        "work_preferences": ["Structured tasks with clear deadlines"],
        "warning_signs": ["Becoming overly rigid", "micromanaging"],
        "when_feeling_stressed": "Under stress, they seek structure and clear expectations.",
    }


@pytest.fixture
def create_question(client, sample_question_data):
    """Factory fixture to create a question"""
    # Counter to ensure unique question_order
    counter = {'value': 0}
    
    def _create_question(**kwargs):
        counter['value'] += 1
        # Use counter for question_order if not explicitly provided
        if 'question_order' not in kwargs:
            kwargs['question_order'] = counter['value']
        qo = kwargs['question_order']
        if 'options' not in kwargs:
            kwargs['options'] = four_options_for_question_order(qo)
        data = {**sample_question_data, **kwargs}
        response = client.post("/questions", json=data)
        assert response.status_code == 201, f"Failed to create question: {response.json()}"
        return response.json()
    return _create_question


@pytest.fixture
def create_option(client, sample_option_data):
    """Factory fixture to create an option"""

    def _create_option(question_id, **kwargs):
        data = {**sample_option_data, "question_id": str(question_id), **kwargs}
        response = client.post("/options", json=data)
        assert response.status_code == 201, f"Failed to create option: {response.json()}"
        return response.json()
    return _create_option


@pytest.fixture
def create_bsp_style(client, sample_bsp_style_data):
    """Factory fixture to create a BSP style"""
    # Counter for unique style_number
    counter = {'value': 0}
    
    def _create_bsp_style(**kwargs):
        counter['value'] += 1
        # Use counter for style_number if not explicitly provided
        if 'style_number' not in kwargs:
            kwargs['style_number'] = counter['value']
        if 'display_order' not in kwargs:
            kwargs['display_order'] = counter['value']
        # Make title unique if not provided
        if 'title' not in kwargs:
            kwargs['title'] = f"The Organizer {counter['value']}"
        
        data = {**sample_bsp_style_data, **kwargs}
        response = client.post("/bsp-styles", json=data)
        assert response.status_code == 201, f"Failed to create BSP style: {response.json()}"
        return response.json()
    return _create_bsp_style
