"""
Application Configuration

Centralized configuration management for the chatbot application.
Reads from environment variables with sensible defaults.
"""

import os
from typing import Optional
from functools import lru_cache
from dotenv import load_dotenv

load_dotenv()


class Settings:
    """Application settings loaded from environment variables"""

    # Environment
    ENVIRONMENT: str = os.getenv("ENVIRONMENT", "dev")
    LOG_LEVEL: str = os.getenv("LOG_LEVEL", "INFO")

    # AWS Region
    AWS_REGION: str = os.getenv("AWS_REGION", "us-east-1")

    # Bedrock Configuration
    BEDROCK_CHAT_MODEL: str = os.getenv(
        "BEDROCK_CHAT_MODEL", "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
    )
    BEDROCK_EMBEDDING_MODEL: str = os.getenv(
        "BEDROCK_EMBEDDING_MODEL", "amazon.titan-embed-text-v2:0"
    )
    # Cheap model used for background thread summarisation (SummaryMaintainer) and title generation.
    BEDROCK_SUMMARY_MODEL: str = os.getenv(
        "BEDROCK_SUMMARY_MODEL", "us.anthropic.claude-haiku-4-5-20251001-v1:0"
    )

    # Bedrock Prompt Management
    BEDROCK_PROMPT_ID: Optional[str] = os.getenv("BEDROCK_PROMPT_ID")
    BEDROCK_PROMPT_VERSION: str = os.getenv("BEDROCK_PROMPT_VERSION", "1")  # Default to version 1
    BEDROCK_COACH_PROMPT_ID: Optional[str] = os.getenv("BEDROCK_COACH_PROMPT_ID")
    BEDROCK_COACH_PROMPT_VERSION: str = os.getenv("BEDROCK_COACH_PROMPT_VERSION", "1")
    ENABLE_BEDROCK_PROMPT_CACHING: bool = (
        os.getenv("ENABLE_BEDROCK_PROMPT_CACHING", "true").lower() == "true"
    )
    USE_COACH_PERSONA_SHELL: bool = (
        os.getenv("USE_COACH_PERSONA_SHELL", "true").lower() == "true"
    )

    # Bedrock Guardrails (optional — guardrails are skipped when BEDROCK_GUARDRAIL_ID is not set)
    BEDROCK_GUARDRAIL_ID     : Optional[str] = os.getenv("BEDROCK_GUARDRAIL_ID")
    BEDROCK_GUARDRAIL_VERSION: str           = os.getenv("BEDROCK_GUARDRAIL_VERSION", "DRAFT")

    # Backend API Configuration (for tool calling)
    BACKEND_API_URL: Optional[str] = os.getenv("BACKEND_API_URL")
    BACKEND_API_KEY: Optional[str] = os.getenv("BACKEND_API_KEY")

    # Database Configuration
    DB_HOST: Optional[str] = os.getenv("DB_HOST")
    DB_PORT: Optional[str] = os.getenv("DB_PORT", "5432")
    DB_NAME: Optional[str] = os.getenv("DB_NAME")
    DB_SECRET_ARN: Optional[str] = os.getenv("DB_SECRET_ARN")

    # RAG Configuration
    RAG_TOP_K: int = int(os.getenv("RAG_TOP_K", "10"))  # Increased to capture all relaetd chunks including definitions
    RAG_MIN_SIMILARITY: float = float(os.getenv("RAG_MIN_SIMILARITY", "0.25"))  # Lower threshold to catch definition chunks
    CHUNK_SIZE: int = int(os.getenv("CHUNK_SIZE", "2000"))  # Increased from 1000 to keep related content together
    CHUNK_OVERLAP: int = int(os.getenv("CHUNK_OVERLAP", "200"))  # Increased from 100 to prevent boundary cuts

    # API Configuration
    API_TITLE: str = "Bispy Bot API"
    API_VERSION: str = "1.0.0"
    CORS_ORIGINS: list = [
        "https://dev.bspblueprint.com",             # dev domain
        "https://staging.bspblueprint.com",         # stage domain
        "https://uat.bspblueprint.com",        # uat domain
        # Local development origins 
        "http://localhost:5173",
        "http://localhost:5174",
        "http://localhost:3000",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:3000",
    ]

    # Audit Export (S3 + presigned URLs)
    AUDIT_EXPORT_BUCKET      : Optional[str] = os.getenv("AUDIT_EXPORT_BUCKET")
    EXPORT_URL_EXPIRY_SECONDS: int           = int(os.getenv("EXPORT_URL_EXPIRY_SECONDS", "3600"))

    # Service-to-service API key for backend team's audit log access.
    # Separate from BACKEND_API_KEY which is for the tool-calling backend.
    AUDIT_BACKEND_API_KEY: Optional[str] = os.getenv("AUDIT_BACKEND_API_KEY")

    # KMS encryption (Thread & Trim — at-rest encryption for messages + summaries)
    # ARN of the Customer Managed Key created by infrastructure/modules/kms/kms_messages_stack.py.
    # Injected as an env var by CDK RuntimeStack at deploy time.
    #
    # Upgrade path (Distilled Memories): this field becomes the *root* CMK ARN.
    # Per-user DEKs will be generated by CryptoClient and stored per user in the DB.
    # The CryptoClient interface (encrypt/decrypt) stays the same; only key_id varies.
    KMS_MESSAGES_KEY_ARN: Optional[str] = os.getenv("KMS_MESSAGES_KEY_ARN")

    # Set to "true" in local development to bypass KMS and store plaintext.
    # crypto.py uses a 4-zero-byte sentinel so dev blobs are still safely
    # round-trippable without a live KMS endpoint.
    # NEVER set to true in staging or production.
    CHATBOT_ENCRYPTION_DISABLED: bool = (
        os.getenv("CHATBOT_ENCRYPTION_DISABLED", "false").lower() == "true"
    )

    # Warm-tier HTTP budget for personalization and peer mention resolution.
    WARM_CONTEXT_HTTP_TIMEOUT: float = float(
        os.getenv("WARM_CONTEXT_HTTP_TIMEOUT", "3")
    )

    # Phase 3 — speculative warm-tier prefetch on borderline fast-path queries.
    ENABLE_SPECULATIVE_WARM_PREFETCH: bool = (
        os.getenv("ENABLE_SPECULATIVE_WARM_PREFETCH", "false").lower() == "true"
    )

    # Distilled user memories (L3)
    ENABLE_MEMORY_RETRIEVAL: bool = (
        os.getenv("ENABLE_MEMORY_RETRIEVAL", "true").lower() == "true"
    )
    ENABLE_MEMORY_EXTRACTION: bool = (
        os.getenv("ENABLE_MEMORY_EXTRACTION", "true").lower() == "true"
    )
    MEMORY_RETRIEVE_TIMEOUT_MS: int = int(os.getenv("MEMORY_RETRIEVE_TIMEOUT_MS", "1200"))
    MEMORY_EXTRACT_MODEL_ID: Optional[str] = os.getenv("MEMORY_EXTRACT_MODEL_ID")
    MEMORY_EMBEDDING_MODEL_ID: Optional[str] = os.getenv("MEMORY_EMBEDDING_MODEL_ID")
    MEMORY_DEFAULT_STATUS: str = os.getenv("MEMORY_DEFAULT_STATUS", "candidate")
    MEMORY_IMPORTANCE_MIN: float = float(os.getenv("MEMORY_IMPORTANCE_MIN", "0.3"))
    # When no memory_consent row exists, treat extraction consent as granted if true.
    # Dev/stage enable this until the Memory Panel consent UI ships.
    MEMORY_CONSENT_DEFAULT_GRANTED: bool = (
        os.getenv("MEMORY_CONSENT_DEFAULT_GRANTED", "false").lower() == "true"
    )

    # Coach coachee profile: mock fixtures until Nest coachee context API ships.
    USE_MOCK_CLIENT_SNAPSHOT: bool = (
        os.getenv("USE_MOCK_CLIENT_SNAPSHOT", "true").lower() == "true"
    )

    # Cognito JWT verification (defence-in-depth).
    # Default OFF: tokens are assumed already validated by the upstream API
    # Gateway Cognito authorizer, so we only decode claims. Enable in any
    # deployment where the chatbot can be reached directly (function URL,
    # internal VPC, direct invoke) so the signature, issuer, and expiry are
    # verified against the Cognito JWKS before any identity is trusted.
    CHATBOT_VERIFY_JWT: bool = (
        os.getenv("CHATBOT_VERIFY_JWT", "false").lower() == "true"
    )
    COGNITO_REGION: str = os.getenv("COGNITO_REGION", os.getenv("AWS_REGION", "us-east-1"))
    COGNITO_USER_POOL_ID: Optional[str] = os.getenv("COGNITO_USER_POOL_ID")
    # Optional explicit overrides — derived from region + pool id when unset.
    COGNITO_ISSUER: Optional[str] = os.getenv("COGNITO_ISSUER")
    COGNITO_JWKS_URL: Optional[str] = os.getenv("COGNITO_JWKS_URL")

    # Feature Flags
    ENABLE_RAG: bool = os.getenv("ENABLE_RAG", "true").lower() == "true"
    ENABLE_CACHING: bool = os.getenv("ENABLE_CACHING", "false").lower() == "true"

    # Redis (Growth Spark daily cache; optional — falls back to in-process memory)
    REDIS_URL: Optional[str] = os.getenv("REDIS_URL")

    @property
    def is_production(self) -> bool:
        """Check if running in production environment"""
        return self.ENVIRONMENT.lower() == "prod"

    @property
    def has_database_config(self) -> bool:
        """Check if database configuration is available"""
        return all([self.DB_HOST, self.DB_NAME, self.DB_SECRET_ARN])

    @property
    def has_encryption_config(self) -> bool:
        """Check if message encryption is available (dev bypass or real KMS key)."""
        return bool(self.KMS_MESSAGES_KEY_ARN) or self.CHATBOT_ENCRYPTION_DISABLED


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """
    Get cached settings instance

    Returns:
        Settings: Application settings singleton
    """
    return Settings()


# Convenience export
settings = get_settings()
