/** Canonical submodule keys — mirror backend `submodule.registry.ts` `SUBMODULE_KEYS`. */
export const SUBMODULE_KEYS = {
	DASHBOARD: "dashboard.dashboard",
	CORPORATION_OVERVIEW_VIEW: "corporation_overview.view",
	CORPORATION_DIRECTORY_ADD: "corporation_directory.add_new_corporation",
	CORPORATION_DIRECTORY_VIEW: "corporation_directory.view_corporation",
	CORPORATION_DIRECTORY_EDIT: "corporation_directory.edit_corporation",
	CORPORATION_DIRECTORY_SUSPEND:
		"corporation_directory.suspend_reinstate_corporation",
	CORPORATION_DIRECTORY_CLOSE: "corporation_directory.close_corporation",
	COMPANY_OVERVIEW_VIEW: "company_overview.view",
	COMPANY_DIRECTORY_ADD: "company_directory.add_new_company",
	COMPANY_DIRECTORY_VIEW: "company_directory.view_company",
	COMPANY_DIRECTORY_EDIT: "company_directory.edit_company",
	COMPANY_DIRECTORY_SUSPEND: "company_directory.suspend_reinstate_company",
	PLANS_PRICING_VIEW: "plans_pricing.view",
	BILLING_MANAGEMENT_VIEW: "billing_management.view_billing",
	BILLING_MANAGEMENT_EDIT: "billing_management.edit_billing",
	BILLING_MANAGEMENT_CANCEL_REINSTATE:
		"billing_management.cancel_reinstate_subscription",
	INVOICE_MANAGEMENT_VIEW: "invoice_management.view_invoices",
	INVOICE_MANAGEMENT_SEND_INDIVIDUAL:
		"invoice_management.send_invoice_individual",
	INVOICE_MANAGEMENT_SEND_BULK: "invoice_management.send_invoice_bulk",
	INVOICE_MANAGEMENT_DOWNLOAD: "invoice_management.download_invoice",
	INVOICE_MANAGEMENT_BULK_DOWNLOAD: "invoice_management.bulk_download_invoices",
	PROMO_CODE_ADD: "promo_code_management.add_new_promo_code",
	PROMO_CODE_VIEW: "promo_code_management.view_promo_code_details",
	PROMO_CODE_EDIT: "promo_code_management.edit_promo_code",
	PROMO_CODE_DELETE: "promo_code_management.delete_promo_code",
	USER_DIRECTORY_INVITE: "user_directory.invite_user_contacts",
	USER_DIRECTORY_VIEW: "user_directory.view_users_contacts",
	USER_DIRECTORY_BULK_UPLOAD: "user_directory.bulk_upload",
	USER_DIRECTORY_EDIT: "user_directory.edit_user",
	USER_DIRECTORY_EDIT_CONTACT: "user_directory.edit_contact",
	USER_DIRECTORY_BLOCK: "user_directory.block_user",
	USER_DIRECTORY_REMOVE: "user_directory.remove_user",
	USER_DIRECTORY_REMOVE_CONTACT: "user_directory.remove_contact",
	USER_DIRECTORY_RESEND_INVITE: "user_directory.resend_invite",
	USER_DIRECTORY_CANCEL_INVITATION: "user_directory.cancel_invitation",
	USER_DIRECTORY_SCHEDULE_SESSION: "user_directory.schedule_session",
	ROLES_PERMISSIONS_VIEW: "roles_permissions.view",
	ROLES_PERMISSIONS_MANAGE: "roles_permissions.manage",
	INVITE_MANAGEMENT_SEND: "invite_management.send_individual_invite",
	INVITE_MANAGEMENT_VIEW: "invite_management.view_users",
	ASSESSMENT_LIST: "assessment.list_view",
	ASSESSMENT_TAKE: "assessment.take_assessment",
	ASSESSMENT_VIEW_RESULT: "assessment.view_result",
	SETTINGS_PROFILE: "settings.profile_overview",
	SETTINGS_SECURITY: "settings.security",
	SETTINGS_PRIVACY: "settings.privacy_data",
} as const;

export type SubmoduleKey = (typeof SUBMODULE_KEYS)[keyof typeof SUBMODULE_KEYS];
