export const SETTINGS_SECURITY_CONTENT = {
	cardTitle: "Security Settings",
	changePasswordTitle: "Change Password",
	changePasswordUpdateButton: "Update",
	twoFactorTitle: "2FA Preference",
	twoFactorDescription: "Implement two-step authentication for your account",
	twoFactorEnabledDescription:
		"Two-step authentication is enabled for your account",
	enableTwoFactorButton: "Enable 2FA",
	disableTwoFactorButton: "Disable 2FA",
	loadError:
		"We couldn't load your security settings. Please refresh or try again later.",
	retryButton: "Retry",
	changePasswordDialogTitle: "Change Password",
	changePasswordDialogSubtitle: "Set a new password for your account",
	passwordRuleTitle: "Password Rule",
	passwordRuleBodyPrefix: "Your new password must be ",
	passwordRuleMinLength: "at least 8 characters",
	passwordRuleMiddle: ", with ",
	passwordRuleCase: "upper & lowercase",
	passwordRuleMiddle2: ", ",
	passwordRuleSymbolOrNumber: "a symbol or a number",
	passwordRuleSuffix: ".",
	fieldCurrentPassword: "Current Password",
	fieldNewPassword: "New Password",
	fieldConfirmPassword: "Confirm Password",
	cancelButton: "Cancel",
	saveButton: "Save & Update",
	savingButton: "Saving…",
	passwordChangeSuccess: "Password updated successfully.",
	mfaDialogTitleEnable: "Two Factor Authentication",
	mfaDialogTitleDisable: "Two Factor Authentication",
	mfaDialogSubtitleEnable: "Enable enhanced security with an OTP.",
	mfaDialogSubtitleDisable:
		"Confirm with a one-time code to disable two-factor authentication.",
	mfaNoteTitle: "Note",
	mfaNoteBody: "We'll send a 6-digit code on your given email.",
	fieldEmail: "Email",
	fieldCode: "Code",
	mfaResendPrompt: "Didn't receive the code?",
	mfaResendLink: "Resend",
	mfaOtpSentToast: "A verification code has been sent to your email.",
	mfaEnabledToast: "Two-factor authentication has been enabled successfully.",
	mfaDisabledToast: "Two-factor authentication has been disabled successfully.",
	mfaSendingCode: "Sending code…",
	mfaVerifying: "Verifying…",
	mfaResending: "Resending…",
} as const;

export const SETTINGS_SECURITY_OTP_CONFIG = {
	codeLength: 6,
	timerDurationSeconds: 180,
} as const;
