export const COGNITO_SUPER_ADMIN_GROUP = "SuperAdmin";
export const COGNITO_CORPORATION_ADMIN_GROUP = "CorporationAdmin";
export const COGNITO_COMPANY_ADMIN_GROUP = "CompanyAdmin";
export const COGNITO_USER_GROUP = "User";

export const USER_DIRECTORY_ALLOWED_GROUPS = [
	COGNITO_SUPER_ADMIN_GROUP,
	COGNITO_CORPORATION_ADMIN_GROUP,
	COGNITO_COMPANY_ADMIN_GROUP,
] as const;

export const ASSESSMENT_DIRECTORY_ALLOWED_GROUPS = [
	COGNITO_USER_GROUP,
	COGNITO_COMPANY_ADMIN_GROUP,
	COGNITO_CORPORATION_ADMIN_GROUP,
] as const;
