/** Shared form input, search, and select placeholder copy. */
export const FORM_PLACEHOLDERS = {
	// Auth & credentials
	enterEmail: "Enter email",
	enterEmailExtended: "Enter your email here",
	enterPassword: "Enter password",
	newPassword: "New Password",
	confirmPassword: "Confirm Password",

	// Generic text inputs
	enterSubject: "Enter the subject",
	typeMessage: "Type your message here.",
	typeNotes: "Type your notes here...",
	enterRoleName: "Enter role name",
	enterRoleDescription: "Enter role-based description here...",
	enterJobRole: "Enter job role",
	enterZipPostalCode: "Enter zip/ postal code",
	enterZipPostalCodeAlt: "Enter ZIP/Postal code",
	addressLine: "Address line",
	enterAddressLine: "Enter address line",
	enterStateProvince: "Enter state/province",
	enterCity: "Enter city",
	enterCountry: "Enter country",
	enterPromoDescription: "Enter promo code description here...",
	recipients: "Fill in email ids of recipients and hit enter",
	teamManagerAutoPopulate: "Team manager name (Auto-populate)",
	conversationName: "Conversation name",
	askAnything: "Ask me anything...",
	dateFormat: "mm-dd-yyyy",

	// Search
	searchGeneric: "Search here...",
	searchByRoleName: "Search by role name here...",
	searchUsernameOrEmail: "Search by username or email...",
	searchContactNameOrEmail: "Search by contact name or email...",
	searchCompanyOrCorporation: "Search by company or corporation name...",
	searchCorporationOrAdmin: "Search by corporation or admin name...",
	searchByCompanyName: "Search by company name...",
	searchByInvoiceIdOrCompany: "Search by invoice id or company…",
	searchByInvoiceId: "Search by invoice id…",
	searchByPromoCodeOrDescription: "Search by promo code here…",
	searchByPromoCodeUsage:
		"Search by user name, email, corporation, or company…",
	searchForCorporation: "Search for corporation",
	searchForCompany: "Search for company",
	searchOrSelectPromoCode: "Search or select promo code",
	searchChats: "Search chats",

	// Select dropdowns
	selectCategory: "Select category",
	selectRoleName: "Select role name",
	selectTeam: "Select team",
	selectTimeZone: "Select time zone",
	selectCorporation: "Select corporation",
	selectCompany: "Select company",
	selectContactType: "Select contact type",
	selectStatus: "Select status",
	selectReason: "Select a reason",
	selectItem: "Select an item",
	selectPlanLevel: "Select plan level",
	planLevelCustom: "Custom",
	selectCompanyType: "Select company type",
	selectOfficeType: "Select office type",
	selectRegion: "Select region",
	selectOperatingRegion: "Select operating region",
	selectIndustry: "Select industry",
	selectIndustryWithPeriod: "Select industry.",
	selectCountry: "Select country",
	selectCity: "Select city",
	selectStateProvince: "Select state/ province",
	selectExpiryDate: "Select expiry date",
	selectPlan: "Select plan",
	selectRole: "Select a role",
	selectClient: "Select a client",
	selectOwnershipType: "Select ownership type",
	selectParentCorporation: "Select parent corporation",
	selectAuthenticationMethod: "Select authentication method",
	selectPasswordPolicy: "Select password policy",
	selectTwoFaRequirement: "Select 2FA requirement",
	selectSessionTimeout: "Select session timeout",
	selectSecurityPosture: "Select security posture",
	selectPrimaryLanguage: "Select primary language",
	selectTrialStartDate: "Select trial start date",

	// Empty states
	noActiveCompanies: "No active companies",

	// Example values
	promoCode: "e.g., BSP100OFF",
	discountPercent: "e.g., 15%, 20%",
	discountFixed: "e.g., 50",
	maxUsage: "e.g. 50, 100",
	ownershipWhollyOwned: "e.g., Wholly Owned",
	companyLegalName: "e.g., Acme Inc.",
	companyLegalNameIndia: "e.g., Acme India Pvt Ltd",
	corporationLegalName: "e.g., Acme Corporation",
	dbaTradeName: "e.g., Acme Co.",
	dbaName: "e.g., Acme Inc.",
	websiteUrl: "e.g., https://www.acme.com",
	phoneFormatted: "e.g., +1 (555) 123-4567",
	phoneSpaced: "e.g., +1 555 123 4567",
	cellPhone: "e.g., +1 234 567-8901",
	firstNameNico: "e.g., Nico",
	firstNameArthur: "e.g., Arthur",
	firstNameMike: "e.g., Mike",
	lastNameRobin: "e.g., Robin",
	lastNameHarold: "e.g., Harold",
	lastNameDavis: "e.g., Davis",
	nicknameNicbin: "e.g., Nicbin",
	nicknameArold: "e.g., Arold",
	nicknameMd: "e.g., MD",
	emailNicoRobin: "e.g., nico_robin@email.com",
	emailArthurHarold: "e.g., arthur_harold@email.com",
	emailMikeDavis: "e.g., mike_davis@email.com",
	jobRoleAdministrator: "e.g., Administrator",
	jobRoleCeo: "e.g., CEO, Corporate Admin",
	jobRoleHrManager: "e.g., HR Manager",
	fullNameMikeDavis: "e.g., Mike Davis",
	employeesCount: "e.g., 25, 50, etc.",
	securityPostureStandard: "Standard",
} as const;

/** Placeholder when a view detail row value is empty or null. */
export const EMPTY_VALUE_PLACEHOLDER = "Not provided";
